### PR TITLE
#53 Add documentation for keyboard events

### PR DESCRIPTION
**Pull request by thSoft**

### CODE REVIEW

**Comment by cmontella** [comment]
Thanks for taking the time to do this.

Do you have time to add some examples? Let me know, if not I can do it and get this merged in.

**Review by cmontella — CHANGES_REQUESTED** [review]
Needs examples

**Comment by thSoft** [comment]
Added examples.

**Review by cmontella — APPROVED** [review]

**Comment by cmontella** [comment]
Thanks!

**Pull request merged**
